# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_test_nlopt <- function() {
    .Call('_PLNmodels_cpp_test_nlopt', PACKAGE = 'PLNmodels')
}

nlopt_optimize_diagonal <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_diagonal', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_diagonal <- function(data, params, B, Omega, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_diagonal', PACKAGE = 'PLNmodels', data, params, B, Omega, config)
}

nlopt_optimize_fixed <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_fixed', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_fixedc <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_fixedc', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_fixedc <- function(data, params, B, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_fixedc', PACKAGE = 'PLNmodels', data, params, B, config)
}

nlopt_optimize_fixedv <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_fixedv', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_fixedv <- function(data, params, B, L, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_fixedv', PACKAGE = 'PLNmodels', data, params, B, L, config)
}

nlopt_optimize_mstep_fixedv <- function(data, params, M, S, config) {
    .Call('_PLNmodels_nlopt_optimize_mstep_fixedv', PACKAGE = 'PLNmodels', data, params, M, S, config)
}

nlopt_optimize_fixedv_unsup <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_fixedv_unsup', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_fixedv_unsup <- function(data, params, B, L, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_fixedv_unsup', PACKAGE = 'PLNmodels', data, params, B, L, config)
}

nlopt_optimize <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep <- function(data, params, B, Omega, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep', PACKAGE = 'PLNmodels', data, params, B, Omega, config)
}

nlopt_optimize_genetic_modeling <- function(init_parameters, Y, X, O, w, C, configuration) {
    .Call('_PLNmodels_nlopt_optimize_genetic_modeling', PACKAGE = 'PLNmodels', init_parameters, Y, X, O, w, C, configuration)
}

nlopt_optimize_rank <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_rank', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_rank <- function(data, params, B, C, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_rank', PACKAGE = 'PLNmodels', data, params, B, C, config)
}

nlopt_optimize_mstep_rank <- function(data, params, M, S, config) {
    .Call('_PLNmodels_nlopt_optimize_mstep_rank', PACKAGE = 'PLNmodels', data, params, M, S, config)
}

nlopt_optimize_rank_unsup <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_rank_unsup', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_rank_unsup <- function(data, params, B, C, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_rank_unsup', PACKAGE = 'PLNmodels', data, params, B, C, config)
}

nlopt_optimize_spherical <- function(data, params, config) {
    .Call('_PLNmodels_nlopt_optimize_spherical', PACKAGE = 'PLNmodels', data, params, config)
}

nlopt_optimize_vestep_spherical <- function(data, params, B, Omega, config) {
    .Call('_PLNmodels_nlopt_optimize_vestep_spherical', PACKAGE = 'PLNmodels', data, params, B, Omega, config)
}

cpp_test_packing <- function() {
    .Call('_PLNmodels_cpp_test_packing', PACKAGE = 'PLNmodels')
}

